const recordException = async (exception) => {

}

export default recordException